services:
  angular:
    build: .
    container_name: angular-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    command: sh -c "cd ToDoList && ng serve --host 0.0.0.0"
