apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # Base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=   # Base64 encoded 'postgres'
